"""Test multi-layer subagent nesting with data provenance verification.

Verifies that engine.delegate() correctly handles a 3-level agent hierarchy
and that numbers reported at each level match the actual outputs from
child agents — no hallucinated values.

    Root Agent
      ├── Child A ── Grandchild A1, A2
      ├── Child B ── Grandchild B1, B2
      └── Child C ── Grandchild C1, C2

Each grandchild generates a random integer wrapped in <number> tags.
Each child assigns unique IDs to its grandchildren and reports back.
The root lists every grandchild result by ID.

Assertions cross-reference JSONL logs across all three levels to verify
that the root's final report contains the exact numbers generated by
each grandchild agent.
"""

import json
import os
import re
from collections import Counter
from pathlib import Path
from typing import Dict, List

import pytest

from engine import delegate
from engine.logging.sink import AsyncFileHandler

LOG_DIR = Path("logs")

TEST_PROMPT = """\
You are a coordinator. Complete the following task using sub-agents.

## Objective

Distribute a random-number task across a 3-level hierarchy to demonstrate
multi-layer sub-agent orchestration.

## Hierarchy Requirements

1. Spawn exactly **3 child agents** (label them Child A, B, and C).
2. Each child must spawn exactly **2 grandchild agents**.

## Per-Agent Instructions (MANDATORY — pass these down verbatim)

You MUST include the following instructions in each child's task description,
and each child MUST include them in each grandchild's task description:

### Grandchildren
Each grandchild generates exactly one random integer in [1, 100] and outputs
ONLY this line (no explanation, no extra text):
    <number>VALUE</number>

### Children
Each child MUST assign a unique two-character ID to each grandchild using
the pattern: {ChildLetter}{Index}.
For example, Child A → A1, A2. Child B → B1, B2. Child C → C1, C2.

Each child collects its two grandchild outputs and reports EXACTLY this format:
    CHILD_REPORT: A1=<number>V1</number> A2=<number>V2</number>
(Replace A1/A2 with the actual IDs, V1/V2 with the actual values.)

### Root (you)
Collect all child reports and output a summary listing EVERY grandchild
by its ID in this exact format:

    GRANDCHILD_RESULTS:
    A1: <number>V1</number>
    A2: <number>V2</number>
    B1: <number>V3</number>
    B2: <number>V4</number>
    C1: <number>V5</number>
    C2: <number>V6</number>

## Rules
- Do NOT fabricate or modify any value reported by sub-agents.
- Every grandchild ID must appear exactly once in the root summary.
- If any errors occur, append an Errors section at the end.
"""


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(autouse=True)
def test_log_prefix(monkeypatch):
    """Use test_*.jsonl prefix instead of run_*.jsonl for test log files."""

    original_init = AsyncFileHandler.__init__

    def patched_init(self, log_dir):
        original_init(self, log_dir)
        self.file_path = self.file_path.with_name(
            self.file_path.name.replace("run_", "test_", 1)
        )

    monkeypatch.setattr(AsyncFileHandler, "__init__", patched_init)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_ID_VALUE_PATTERN = re.compile(
    r"([A-Z]\d+)\s*[=:]\s*<number>(\d+)</number>", re.IGNORECASE
)


def _extract_numbers(text: str) -> List[int]:
    """Extract all integers from <number>...</number> tags."""
    return [int(m) for m in re.findall(r"<number>(\d+)</number>", text)]


def _parse_id_value_pairs(text: str) -> Dict[str, int]:
    """Extract {ID: number} pairs from text (e.g. 'A1: <number>42</number>')."""
    return {m[0].upper(): int(m[1]) for m in _ID_VALUE_PATTERN.findall(text)}


def _load_agent_results_from_logs() -> Dict[int, List[str]]:
    """Parse the latest test log file and group agent results by depth.

    Uses ``agent_finalize`` events which are logged by every agent upon
    completion — including agents that entered WAITING_FOR_CHILDREN and
    resumed via ``children_settled`` (these do NOT emit ``child_run_success``).

    Returns:
        {depth: [result_text, ...]} for depth > 0 only.
    """
    log_files = sorted(
        LOG_DIR.glob("test_*.jsonl"),
        key=os.path.getmtime,
        reverse=True,
    )
    assert log_files, f"No test log files (test_*.jsonl) found in {LOG_DIR.resolve()}"

    results: Dict[int, List[str]] = {}
    with open(log_files[0]) as f:
        for line in f:
            entry = json.loads(line)
            if entry.get("event_type") != "agent_finalize":
                continue
            depth = entry.get("depth", 0)
            if depth == 0:
                continue
            result_text = entry.get("data", {}).get("result", "")
            results.setdefault(depth, []).append(result_text)

    return results


# ---------------------------------------------------------------------------
# Test
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_multilayer_subagent():
    result = await delegate(TEST_PROMPT)

    assert result.success, f"delegate failed: {result.error}"
    assert result.content, "delegate returned empty content"

    agent_results = _load_agent_results_from_logs()

    # ===== Layer 1: Grandchildren (depth=2) =====
    grandchild_outputs = agent_results.get(2, [])
    assert len(grandchild_outputs) == 6, (
        f"Expected 6 grandchild agents (depth=2), found {len(grandchild_outputs)}"
    )

    grandchild_numbers: List[int] = []
    for output in grandchild_outputs:
        nums = _extract_numbers(output)
        assert len(nums) == 1, (
            f"Grandchild should output exactly 1 <number> tag, "
            f"found {len(nums)} in: {output[:200]}"
        )
        assert 1 <= nums[0] <= 100, (
            f"Grandchild number out of range [1, 100]: {nums[0]}"
        )
        grandchild_numbers.append(nums[0])

    # ===== Layer 2: Children (depth=1) =====
    child_outputs = agent_results.get(1, [])
    assert len(child_outputs) == 3, (
        f"Expected 3 child agents (depth=1), found {len(child_outputs)}"
    )

    child_id_value_map: Dict[str, int] = {}
    for output in child_outputs:
        parsed = _parse_id_value_pairs(output)
        assert len(parsed) == 2, (
            f"Child should report exactly 2 ID=value pairs, "
            f"found {len(parsed)} in: {output[:200]}"
        )
        child_id_value_map.update(parsed)

    # Verification 1: children's reported numbers match grandchild outputs
    assert Counter(grandchild_numbers) == Counter(child_id_value_map.values()), (
        f"Data provenance mismatch (depth=2 → depth=1)!\n"
        f"  Grandchild outputs: {sorted(grandchild_numbers)}\n"
        f"  Children claimed:   {sorted(child_id_value_map.values())}"
    )

    # ===== Layer 3: Root (depth=0) =====
    root_mapping = _parse_id_value_pairs(result.content)

    assert len(root_mapping) == 6, (
        f"Root should list exactly 6 grandchild IDs, "
        f"found {len(root_mapping)}: {list(root_mapping.keys())}"
    )

    expected_ids = {"A1", "A2", "B1", "B2", "C1", "C2"}
    assert set(root_mapping.keys()) == expected_ids, (
        f"Root IDs mismatch: expected {sorted(expected_ids)}, "
        f"got {sorted(root_mapping.keys())}"
    )

    # Verification 2: root's ID→number mapping matches children's reports
    assert root_mapping == child_id_value_map, (
        f"Data provenance mismatch (depth=1 → depth=0)!\n"
        f"  Children reported: {child_id_value_map}\n"
        f"  Root reported:     {root_mapping}"
    )
